import assert from 'node:assert/strict';
import {buildProductContract} from '../src/services/projects/siteProductContract.js';
import {createGenerationBudget,normalizeProductPlan,safeGeneratedPath} from '../src/services/projects/siteBuilderPolicy.js';
const contract=buildProductContract({template:'delivery'});
assert.equal(contract.hardRequirement,true);
for(const capability of ['persistent-cart','checkout','payment-change','order-validation','whatsapp-order-summary'])assert.ok(contract.requiredExperiences.includes(capability));
assert.match(contract.previewPolicy,/demonstração/);
assert.equal(buildProductContract({segment:'Clínica odontológica'}).type,'clinic');
assert.equal(buildProductContract({segment:'Imobiliária'}).type,'realestate');
const a={id:'a',targetFiles:['lib/cart.js'],dependsOn:[]};
const b={id:'b',targetFiles:['components/Shop/Shop.jsx','components/Shop/Shop.module.css'],dependsOn:['a']};
assert.equal(normalizeProductPlan({tasks:[b,a]}).tasks[0].id,'a');
assert.throws(()=>normalizeProductPlan({tasks:Array.from({length:17},(_,i)=>({...a,id:String(i)}))}));
assert.throws(()=>normalizeProductPlan({tasks:[a,{...b,targetFiles:['lib/cart.js']}]}));
assert.throws(()=>normalizeProductPlan({tasks:[{...a,dependsOn:['b']},b]}));
assert.throws(()=>normalizeProductPlan({tasks:[a,{...b,targetFiles:['../../outside.js']}]}));
assert.throws(()=>normalizeProductPlan({tasks:[a,{...b,targetFiles:['data/siteData.js']}]}));
assert.equal(safeGeneratedPath('.env'),'');
assert.equal(safeGeneratedPath('package.json'),'');
assert.deepEqual(normalizeProductPlan({tasks:[a,{...b,targetFiles:[...b.targetFiles,'app/page.jsx','app/layout.jsx','app/globals.css']}]}).tasks[1].targetFiles,b.targetFiles);
const budget=createGenerationBudget();let invocations=0;
for(let i=0;i<7;i++)await budget.run('stage',{},async request=>{invocations++;assert.equal(request.retries,0);return {text:'ok'}});
await assert.rejects(budget.run('extra',{},async()=>{invocations++}),{code:'AI_BUDGET'});
assert.equal(invocations,7);
const failed=createGenerationBudget(1);
await assert.rejects(failed.run('failed',{},async()=>{throw Error('timeout')}));
assert.equal(failed.remaining,0);
console.log('Builder policy tests passed: contracts, ownership, dependencies, path safety and strict call budget.');
