import fs from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { generateSiteWithDefaultProvider as generate } from "../ai/siteProviderService.js";
import { runVisualQualityAudit } from "./siteVisualQa.js";

const execFileAsync=promisify(execFile);
const clean=(v,n=200000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,n);
const modelFor=s=>s.siteVariant==="testelead"?"":clean(process.env.LEADFLOW_SITE_MODEL||"",300);
const CORE_FILES=new Set(["app/page.jsx","app/page.js","app/layout.jsx","app/layout.js","app/globals.css","package.json"]);

function safePath(v){const p=String(v||"").replace(/\\/g,"/").replace(/^\.\//,"").trim();return !p||p.startsWith("/")||p.includes("..")||!/^[-A-Za-z0-9_./@()[\]]+$/.test(p)?"":p}
function parseJson(text){const raw=clean(text,120000).replace(/<think>[\s\S]*?<\/think>/gi,"").replace(/^\s*```(?:json)?/i,"").replace(/```\s*$/,"").trim();const a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a<0||b<a)throw new Error("Planner não retornou JSON.");return JSON.parse(raw.slice(a,b+1))}
function parseFiles(text){const raw=clean(text,400000).replace(/<think>[\s\S]*?<\/think>/gi,""),files=[];const re=/<FILE\s+path=["']([^"']+)["']\s*>\s*([\s\S]*?)\s*<\/FILE>/gi;let m;while((m=re.exec(raw))){const p=safePath(m[1]);if(p)files.push({path:p,content:m[2]})}if(!files.length)throw new Error("Worker não retornou arquivos.");return files}
function sanitizeGeneratedFiles(files){return files.map(file=>{let content=String(file.content||"");if(/\.css$/i.test(file.path)){content=content.replace(/\r/g,"").replace(/^\s*(background|color|padding|margin|display|width|height|border|font-size|font-weight|line-height|gap|position|top|right|bottom|left|opacity|transform|transition)\s*$/gmi,"").replace(/(^|\n)(\s*)([a-z-]+)\s*\n(\s*})/gi,"$1$2$4").replace(/\n{3,}/g,"\n\n")}return{...file,content}})}
function violations(files){const e=[];for(const f of files){if(/\.(ts|tsx)$/.test(f.path))e.push("TypeScript: "+f.path);if(/\.css$/.test(f.path)&&/@tailwind|@apply\b/.test(f.content))e.push("Tailwind: "+f.path);if(/\.(jsx|js)$/.test(f.path)&&/\sstyle\s*=\s*\{/.test(f.content))e.push("CSS inline: "+f.path)}return e}
function taskFiles(files){return files.filter(f=>!CORE_FILES.has(f.path)&&!/^docs\//.test(f.path))}
async function apply(root,files,{allowCore=false}={}){files=sanitizeGeneratedFiles(files);if(!allowCore)files=taskFiles(files);const e=violations(files);if(e.length){const err=new Error("Contrato técnico violado: "+e.join(" | "));err.code="TECH_CONTRACT";err.violations=e;throw err}for(const f of files){const target=path.join(root,f.path);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,f.content,"utf8")}return files}
async function manifest(root){const out=[];async function walk(dir,rel=""){let ents=[];try{ents=await fs.readdir(dir,{withFileTypes:true})}catch{return}for(const x of ents){if(["node_modules",".next",".leadflow-build","public"].includes(x.name))continue;const r=rel?rel+"/"+x.name:x.name,p=path.join(dir,x.name);if(x.isDirectory())await walk(p,r);else if(/\.(jsx|js|css|json|mjs)$/.test(x.name))out.push(r)}}await walk(root);return out.slice(0,180)}
async function contextFiles(root,n=18){const names=await manifest(root),preferred=names.filter(x=>/^(app|components|data|lib)\//.test(x)).slice(-n),out=[];for(const name of preferred){try{out.push({path:name,content:clean(await fs.readFile(path.join(root,name),"utf8"),6000)})}catch{}}return out}
async function setup(root,name){for(const x of ["app","components","data","lib","docs"])await fs.rm(path.join(root,x),{recursive:true,force:true});await fs.mkdir(path.join(root,"app"),{recursive:true});await fs.writeFile(path.join(root,"app","layout.jsx"),'import "./globals.css";\nexport const metadata={title:"Site em construção"};\nexport default function RootLayout({children}){return <html lang="pt-BR"><body>{children}</body></html>}\n',"utf8");await fs.writeFile(path.join(root,"app","globals.css"),':root{color-scheme:light}*{box-sizing:border-box}html,body{margin:0;padding:0}body{min-height:100vh}a{color:inherit;text-decoration:none}img{max-width:100%;height:auto}\n',"utf8");await fs.writeFile(path.join(root,"app","page.jsx"),'export default function Page(){return <main>Construindo experiência…</main>}\n',"utf8");const pkg={name:String(name||"leadflow-site").toLowerCase().replace(/[^a-z0-9-]/g,"-")||"leadflow-site",version:"1.0.0",private:true,scripts:{dev:"next dev",build:"next build",start:"next start"},dependencies:{next:"latest",react:"latest","react-dom":"latest"}};await fs.writeFile(path.join(root,"package.json"),JSON.stringify(pkg,null,2));await fs.writeFile(path.join(root,"generation-format.json"),JSON.stringify({format:"autonomous-builder-v6-isolated-workers",generatedAt:new Date().toISOString()},null,2))}
async function nextBin(root){try{const p=path.join(root,"node_modules","next","dist","bin","next");await fs.access(p);return p}catch{return path.join(process.cwd(),"node_modules","next","dist","bin","next")}}
async function deterministicRepair(root){const names=await manifest(root);for(const name of names){const target=path.join(root,name);if(/\.css$/i.test(name)){try{const raw=await fs.readFile(target,"utf8"),fixed=sanitizeGeneratedFiles([{path:name,content:raw}])[0].content;if(fixed!==raw)await fs.writeFile(target,fixed,"utf8")}catch{}}if(/\.(jsx|js)$/.test(name)){try{let raw=await fs.readFile(target,"utf8");if(/\b(useState|useEffect|useMemo|useCallback|useRef|useReducer|useContext|useLayoutEffect)\b/.test(raw)&&!/^[\s\n]*["']use client["'];/.test(raw))raw='"use client";\n'+raw;const imports=[...raw.matchAll(/from\s+["'](\.\.?\/[^"']+\.module\.css)["']/g)];for(const m of imports){const css=path.resolve(path.dirname(target),m[1]);try{await fs.access(css)}catch{await fs.mkdir(path.dirname(css),{recursive:true});await fs.writeFile(css,"/* LeadFlow: arquivo restaurado automaticamente; o refinamento visual pode completá-lo. */\n","utf8")}}await fs.writeFile(target,raw,"utf8")}catch{}}}}
async function build(root){await deterministicRepair(root);const bin=await nextBin(root);await fs.rm(path.join(root,".leadflow-build"),{recursive:true,force:true});try{const r=await execFileAsync(process.execPath,[bin,"build"],{cwd:root,timeout:180000,maxBuffer:5e6,env:{...process.env,NODE_ENV:"production",NEXT_TELEMETRY_DISABLED:"1",LEADFLOW_BUILD_DIST_DIR:".leadflow-build"}});return{ok:true,log:clean((r.stdout||"")+"\n"+(r.stderr||""),30000),nextBin:bin}}catch(e){return{ok:false,log:clean((e.stdout||"")+"\n"+(e.stderr||"")+"\n"+e.message,30000),nextBin:bin}}}
function facts(s){return{name:s.brandName,segment:s.segment,city:s.city,address:s.address,phone:s.phone,whatsapp:s.whatsapp,instagram:s.instagram,mapsLink:s.mapsLink,rating:s.rating,reviews:s.reviews,hours:s.hours,images:s.images,description:s.sourceDescription||s.description,audience:s.audience,pageJob:s.pageJob,skills:s.skills||[]}}
function base(s,timeout){return{model:modelFor(s),siteVariant:s.siteVariant||"leadflow",siteRole:"builder",timeoutMs:Number(timeout||process.env.LEADFLOW_SITE_TASK_TIMEOUT_MS||120000),retries:0}}
function plannerRequest(s,instruction,images){return{...base(s,120000),temperature:.8,maxTokens:5000,images,systemPrompt:"Você é o diretor criativo e de produto. Decida livremente o melhor produto digital para o negócio. Não existe template, blueprint ou lista de seções. Decomponha sua solução SOMENTE em tarefas que produzam partes reais do produto. Não crie tarefas de documentação, checklist, relatório ou planejamento abstrato. Cada tarefa deve ser pequena, visual/funcional e possuir arquivos próprios; app/page.jsx, app/layout.jsx e app/globals.css serão montados depois por um integrador. Não escreva código. Responda apenas JSON.",prompt:`CONTEXTO: ${JSON.stringify(facts(s))}\nPEDIDO: ${clean(instruction,5000)}\nRetorne {"concept":"...","productVision":"...","visualDirection":"...","tasks":[{"id":"...","title":"...","goal":"...","targetFiles":["components/X/X.jsx","components/X/X.module.css"],"dependsOn":[]}]} com no máximo 12 tarefas reais de construção.`}}
function normalizePlan(raw){const tasks=(Array.isArray(raw.tasks)?raw.tasks:[]).filter(t=>!/(checklist|documenta|relat[oó]rio|roteiro de atualiza|planejar seo|m[eé]trica)/i.test(String(t.title||""))).slice(0,12).map((t,i)=>({id:clean(t.id,50)||"task-"+(i+1),title:clean(t.title,120)||"Tarefa "+(i+1),goal:clean(t.goal,2200),targetFiles:(Array.isArray(t.targetFiles)?t.targetFiles:[]).map(safePath).filter(p=>p&&!CORE_FILES.has(p)&&!/^docs\//.test(p)).slice(0,8),dependsOn:Array.isArray(t.dependsOn)?t.dependsOn.map(x=>clean(x,50)).filter(Boolean):[]}));if(!tasks.length)throw new Error("Planner não criou tarefas de produto.");return{concept:clean(raw.concept,1000),productVision:clean(raw.productVision,2500),visualDirection:clean(raw.visualDirection,2500),tasks}}
function workerRequest(s,plan,task,tree,ctx,images,recovery=false){const targets=task.targetFiles?.length?task.targetFiles.join(", "):"crie componentes/data/lib próprios para esta tarefa";return{...base(s,recovery?150000:120000),temperature:.72,maxTokens:Number(process.env.LEADFLOW_SITE_TASK_MAX_TOKENS||5000),images,systemPrompt:"Você é um worker especialista. Execute SOMENTE sua tarefa. Você tem liberdade criativa total dentro dela, mas NÃO pode editar app/page.jsx, app/layout.jsx, app/globals.css, package.json, arquivos de outros workers ou criar documentação. Gere apenas os arquivos completos da sua responsabilidade. Next.js App Router + React, JavaScript/JSX + CSS Modules; sem TypeScript, Tailwind, CSS-in-JS ou style={{}}. Se usar hooks ou eventos, inclua \"use client\". Cada import de .module.css deve vir acompanhado do respectivo arquivo CSS. Saída exclusiva: <FILE path=\"...\">conteúdo</FILE>.",prompt:`VISÃO: ${plan.productVision}\nCONCEITO: ${plan.concept}\nDIREÇÃO: ${plan.visualDirection}\nNEGÓCIO: ${JSON.stringify(facts(s))}\nTAREFA: ${task.title}\nOBJETIVO: ${task.goal}\nARQUIVOS SOB SUA RESPONSABILIDADE: ${targets}\nARQUIVOS JÁ EXISTENTES: ${JSON.stringify(tree)}\nCONTEXTO:\n${ctx.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n")}\n${recovery?"Esta é uma recuperação de tarefa que falhou antes. Seja objetivo e conclua somente os arquivos necessários.":""}`}}
function integratorRequest(s,plan,tree,ctx,failed=[]){return{...base(s,150000),temperature:.55,maxTokens:8000,systemPrompt:"Você é o integrador final do produto. Os workers já criaram componentes independentes. Sua função é montar a aplicação coerente e funcional sem redesenhar os componentes. Você é o ÚNICO autorizado a editar app/page.jsx, app/layout.jsx e app/globals.css. Corrija também imports/exports estritamente necessários. Next.js App Router, JavaScript/JSX, CSS Modules, sem TypeScript/Tailwind/CSS inline. Garanta que hooks estejam em Client Components. Retorne somente arquivos completos no protocolo <FILE path=\"...\">...</FILE>.",prompt:`VISÃO: ${plan.productVision}\nDIREÇÃO: ${plan.visualDirection}\nNEGÓCIO: ${JSON.stringify(facts(s))}\nARQUIVOS EXISTENTES: ${JSON.stringify(tree)}\nTAREFAS QUE NÃO CONSEGUIRAM CONCLUIR: ${failed.map(x=>x.title).join(" | ")||"nenhuma"}\nCONTEÚDO DOS ARQUIVOS:\n${ctx.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n")}\nIntegre agora o produto. Não crie checklists nem documentação.`}}
function repairRequest(s,plan,problem,tree,ctx){return{...base(s,150000),temperature:.25,maxTokens:7000,systemPrompt:"Você é o engenheiro de correção. Corrija somente os erros reais do build. Preserve design e conteúdo. Pode editar os arquivos diretamente envolvidos no erro. Next.js + JavaScript/JSX + CSS Modules; sem TS/Tailwind/CSS inline. Se um JSX importar CSS Module, mantenha/crie o CSS correspondente. Se usar React hooks, marque como Client Component. Retorne somente arquivos completos <FILE path=\"...\">...</FILE>.",prompt:`VISÃO: ${plan.productVision}\nERRO REAL:\n${clean(problem,12000)}\nARQUIVOS: ${JSON.stringify(tree)}\n${ctx.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n")}`}}
function qaPlan(plan){return{concept:plan.concept||"autonomous",components:[],creativeThesis:plan.productVision||"",visualSystem:plan.visualDirection||"",conversionStrategy:"Autônoma",imageStrategy:"Autônoma",responsiveStrategy:"Autônoma",designSystem:{}}}
async function runWorker({s,plan,task,root,images,progress,index,total,recovery=false}){const tree=await manifest(root),ctx=await contextFiles(root);if(!recovery)await progress({phase:"task",title:(index+1)+"/"+total+" · "+task.title,detail:task.goal,kind:"agent"});const req=workerRequest(s,plan,task,tree,ctx,index<3?images:[],recovery);req.onAttempt=e=>progress({phase:"ai",title:task.title+" · "+e.status,detail:[e.model,e.elapsedMs&&Math.round(e.elapsedMs/1000)+"s"].filter(Boolean).join(" · "),kind:"model"});let files=parseFiles((await generate(req)).text);const wanted=new Set(task.targetFiles||[]);if(wanted.size)files=files.filter(f=>wanted.has(f.path));files=await apply(root,files);if(!files.length)throw new Error("Worker não produziu arquivos permitidos para a tarefa.");for(const f of files)await progress({phase:"files",title:"Created/Updated "+f.path,detail:"Tarefa concluída: "+task.title,kind:"file",file:f.path,code:clean(f.content,1200)});return files}

export async function generateAutonomousSite(options={}){
 const progress=async e=>{try{await options.onProgress?.(e)}catch{}},s=options.siteData||{},root=path.resolve(process.cwd(),options.folderPath),images=(options.visualImages||[]).filter(x=>x?.dataUrl).slice(0,4);
 await setup(root,options.folderName);await progress({phase:"plan",title:"Diretor autônomo planejando",detail:"O diretor decide o produto e divide apenas trabalho real de construção entre workers isolados.",kind:"agent"});
 let plan;try{const pr=plannerRequest(s,options.instruction||"",images);pr.onAttempt=e=>progress({phase:"ai",title:"Planner · "+e.status,detail:[e.model,e.elapsedMs&&Math.round(e.elapsedMs/1000)+"s"].filter(Boolean).join(" · "),kind:"model"});plan=normalizePlan(parseJson((await generate(pr)).text))}catch(error){await progress({phase:"plan",title:"Planner indisponível · contingência",detail:clean(error?.message||error,700),kind:"agent"});plan={concept:"Experiência comercial autoral",productVision:"Criar uma experiência digital sob medida, visual e funcional, usando dados reais e liberdade criativa.",visualDirection:"Autoral, responsiva e orientada ao negócio.",tasks:[{id:"hero",title:"Criar experiência principal",goal:"Criar uma abertura visual forte e específica para o negócio.",targetFiles:["components/Hero/Hero.jsx","components/Hero/Hero.module.css"],dependsOn:[]},{id:"content",title:"Criar experiência de conteúdo e conversão",goal:"Criar um bloco rico de conteúdo e conversão adequado ao negócio.",targetFiles:["components/Experience/Experience.jsx","components/Experience/Experience.module.css"],dependsOn:[]},{id:"contact",title:"Criar contato e ação final",goal:"Criar experiência final de contato/localização/ação coerente com o negócio.",targetFiles:["components/Contact/Contact.jsx","components/Contact/Contact.module.css"],dependsOn:[]}]}}
 await progress({phase:"plan",title:"Plano autoral criado",detail:plan.tasks.length+" tarefas reais: "+plan.tasks.map(x=>x.title).join(" → "),kind:"agent"});
 const failed=[];for(let i=0;i<plan.tasks.length;i++){try{await runWorker({s,plan,task:plan.tasks[i],root,images,progress,index:i,total:plan.tasks.length})}catch(error){failed.push(plan.tasks[i]);await progress({phase:"task",title:plan.tasks[i].title+" · pendente",detail:clean(error?.message||error,700)+" · será recuperada antes da integração.",kind:"agent"})}}
 if(failed.length){await progress({phase:"recovery",title:"Recuperando tarefas pendentes",detail:failed.length+" tarefa(s) terão uma segunda chamada curta antes da integração.",kind:"agent"});for(const task of [...failed]){try{await runWorker({s,plan,task,root,images:[],progress,index:plan.tasks.indexOf(task),total:plan.tasks.length,recovery:true});failed.splice(failed.indexOf(task),1)}catch(error){await progress({phase:"recovery",title:task.title+" · recuperação indisponível",detail:clean(error?.message||error,600),kind:"agent"})}}}
 await progress({phase:"integrate",title:"Integrador montando a aplicação",detail:"Workers terminaram. Agora uma chamada dedicada monta rotas, imports, layout e composição final sem apagar o trabalho independente.",kind:"agent"});
 {const req=integratorRequest(s,plan,await manifest(root),await contextFiles(root,40),failed);req.onAttempt=e=>progress({phase:"ai",title:"Integrador · "+e.status,detail:[e.model,e.elapsedMs&&Math.round(e.elapsedMs/1000)+"s"].filter(Boolean).join(" · "),kind:"model"});const files=parseFiles((await generate(req)).text);await apply(root,files,{allowCore:true});for(const f of files)await progress({phase:"files",title:"Integrated "+f.path,detail:"Integração final",kind:"file",file:f.path,code:clean(f.content,1000)})}
 let built=await build(root);for(let i=0;!built.ok&&i<2;i++){await progress({phase:"build",title:"Build falhou · correção dirigida",detail:clean(built.log,1800),kind:"command"});let files;try{files=parseFiles((await generate(repairRequest(s,plan,built.log,await manifest(root),await contextFiles(root,35)))).text)}catch(error){await progress({phase:"build",title:"Corretor indisponível",detail:clean(error?.message||error,700),kind:"agent"});break}await apply(root,files,{allowCore:true});built=await build(root)}
 if(!built.ok)throw new Error("Build não estabilizou: "+clean(built.log,4000));
 await progress({phase:"build",title:"✓ Build concluído",detail:"Workers isolados, integração concluída e projeto compilado.",kind:"command"});
 let quality={available:false,pass:true,score:null,threshold:Number(process.env.LEADFLOW_SITE_QUALITY_MIN_SCORE||78)};if(options.visualQa!==false){quality=await runVisualQualityAudit({root,nextBin:built.nextBin,site:s,plan:qaPlan(plan)});if(quality.available&&!quality.pass){const issues=[quality.summary,...(quality.issues||[]).map(x=>"["+x.severity+"] "+x.component+": "+x.instruction)].join("\n");await progress({phase:"repair",title:"QA visual pediu refinamento",detail:"QA "+quality.score+"/"+quality.threshold,kind:"browser"});try{const files=parseFiles((await generate(repairRequest(s,plan,issues,await manifest(root),await contextFiles(root,35)))).text);await apply(root,files,{allowCore:true});built=await build(root);if(built.ok)quality=await runVisualQualityAudit({root,nextBin:built.nextBin,site:s,plan:qaPlan(plan)})}catch{}}}
 await fs.rm(path.join(root,".leadflow-build"),{recursive:true,force:true});if(!built.ok)throw new Error("Build falhou após QA.");return{plan:{...qaPlan(plan),tasks:plan.tasks,productVision:plan.productVision},format:"autonomous-builder-v6-isolated-workers",buildOk:true,quality};
}
