import fs from "node:fs/promises";
import path from "node:path";
import { deflateRawSync } from "node:zlib";
import { resolveProjectFolder } from "./projectStore.js";
const SKIP=new Set(["node_modules",".next",".git"]);let crcTable=null;
function table(){if(crcTable)return crcTable;crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}return crcTable}
function crc32(buffer){let crc=0xFFFFFFFF;const values=table();for(const byte of buffer)crc=values[(crc^byte)&0xFF]^(crc>>>8);return(crc^0xFFFFFFFF)>>>0}
function dosDateTime(date=new Date()){const year=Math.max(1980,date.getFullYear());return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),day:((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()}}
async function walk(root,current=root){const entries=await fs.readdir(current,{withFileTypes:true});const files=[];for(const entry of entries){if(SKIP.has(entry.name))continue;const absolute=path.join(current,entry.name);if(entry.isDirectory())files.push(...await walk(root,absolute));else if(entry.isFile())files.push({absolute,relative:path.relative(root,absolute).replace(/\\/g,"/")})}return files}
export async function createProjectZip(folderPath){const root=resolveProjectFolder(folderPath);if(!root)throw new Error("O projeto ainda não possui arquivos exportáveis.");const files=await walk(root);const locals=[];const centrals=[];let offset=0;const stamp=dosDateTime();for(const file of files){const raw=await fs.readFile(file.absolute);const compressed=deflateRawSync(raw,{level:6});const name=Buffer.from(file.relative,"utf8");const crc=crc32(raw);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(8,8);local.writeUInt16LE(stamp.time,10);local.writeUInt16LE(stamp.day,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(name.length,26);local.writeUInt16LE(0,28);locals.push(local,name,compressed);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0x0800,8);central.writeUInt16LE(8,10);central.writeUInt16LE(stamp.time,12);central.writeUInt16LE(stamp.day,14);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(raw.length,24);central.writeUInt16LE(name.length,28);central.writeUInt16LE(0,30);central.writeUInt16LE(0,32);central.writeUInt16LE(0,34);central.writeUInt16LE(0,36);central.writeUInt32LE(0,38);central.writeUInt32LE(offset,42);centrals.push(central,name);offset+=local.length+name.length+compressed.length}const centralBuffer=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralBuffer.length,12);end.writeUInt32LE(offset,16);end.writeUInt16LE(0,20);return Buffer.concat([...locals,centralBuffer,end])}
